meta_product_name: "Ilia Zolas"
meta_title: "Ilia Zolas"
meta_description: "Digital Marketer and Full Stack Developer"
meta_image: "iliazolas-previews.png" # should exist in `app/assets/images/`
twitter_account: "@iliazolas"   # required for Twitter Cards